// examples/pet-client-vue/src/App.vue
<script setup lang="ts">
import { ref } from 'vue';
import { AxiosQuery } from './api';
import { Status } from './api/axios-client';
let status = ref<Status>(Status.Sold);
const { isLoading, isError, data, error } =
  AxiosQuery.Query.useFindPetsByStatusQuery({
    status: [status] as any,
  });
</script>

<template>
  <div style="display: block">
    <div>Status: {{ status }}</div>
    <div>
      <input
        type="radio"
        name="status"
        id="Sold"
        v-bind:value="Status.Sold"
        v-model="status"
      /><label for="Sold">Sold</label>
      <input
        type="radio"
        name="status"
        id="Available"
        v-bind:value="Status.Available"
        v-model="status"
      /><label for="Available">Available</label>
      <input
        type="radio"
        name="status"
        id="Pending"
        v-model="status"
        v-bind:value="Status.Pending"
      /><label for="Pending">Pending</label>
    </div>
  </div>
  <span v-if="isLoading">Loading...</span>
  <span v-else-if="isError">Error: {{ (error as any).message }}</span>
  <!-- We can assume by this point that `isSuccess === true` -->
  <ul v-else>
    <li v-for="pet in data ?? []">{{ pet.name }}</li>
  </ul>
</template>

<style scoped>
header {
  line-height: 1.5;
}

.logo {
  display: block;
  margin: 0 auto 2rem;
}

@media (min-width: 1024px) {
  header {
    display: flex;
    place-items: center;
    padding-right: calc(var(--section-gap) / 2);
  }

  .logo {
    margin: 0 2rem 0 0;
  }

  header .wrapper {
    display: flex;
    place-items: flex-start;
    flex-wrap: wrap;
  }
}
</style>

// examples/pet-client/src/App.tsx
import React from 'react';
import './App.css';
import { AxiosQuery } from './api';
import { Status } from './api/axios-client';

function App() {
  const pets1Query = AxiosQuery.Query.useFindPetsByStatusQuery({
    status: [Status.Pending, Status.Sold],
  });
  const pets2Query = AxiosQuery.Query.useFindPetsByStatusQuery({
    status: [Status.Pending, Status.Sold, Status.Available],
  });
  return (
    <div className="App">
      <div
        style={{
          display: 'flex',
          flexDirection: 'row',
          justifyContent: 'stretch',
          width: '100%',
        }}
      >
        <div style={{ flex: 1 }}>
          <h1>Pets</h1>
          {pets1Query.isLoading && 'Loading...'}
          {pets1Query.isError && pets1Query.error}
          <ol>
            {pets1Query.data?.map((pet, index) => (
              <li key={index}>{pet.name}</li>
            ))}
          </ol>
        </div>
        <div style={{ flex: 1 }}>
          <h1>Pets</h1>
          {pets2Query.isLoading && 'Loading...'}
          {pets2Query.isError && pets2Query.error}
          <ol>
            {pets2Query.data?.map((pet, index) => (
              <li key={index}>{pet.name}</li>
            ))}
          </ol>
        </div>
      </div>
    </div>
  );
}

export default App;
